// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_1rzIvVD4Lv3XNFvk0Xeh3YmJTXsS4k',
    appId: '1:309304960212:web:a02d0534cee1624b2e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    authDomain: 'tap-map-6c884.firebaseapp.com',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    measurementId: 'G-GDX9VKQ3ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf1gBR96e1qgKr1rvZIA7POxvGS2caVk8',
    appId: '1:309304960212:android:a4be5c5e4e9df1e22e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4TJcm0oz3_3Xk3fVXrXW9fi4gJMqddY',
    appId: '1:309304960212:ios:06b647047592d0952e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    iosBundleId: 'com.example.mapExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4TJcm0oz3_3Xk3fVXrXW9fi4gJMqddY',
    appId: '1:309304960212:ios:06b647047592d0952e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    iosBundleId: 'com.example.mapExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT_1rzIvVD4Lv3XNFvk0Xeh3YmJTXsS4k',
    appId: '1:309304960212:web:2dd80c56422ed5f02e8741',
    messagingSenderId: '309304960212',
    projectId: 'tap-map-6c884',
    authDomain: 'tap-map-6c884.firebaseapp.com',
    storageBucket: 'tap-map-6c884.firebasestorage.app',
    measurementId: 'G-GHQ5M910LK',
  );
}
